#各ブロックの風の有効範囲と強さ
#limit = 最大距離
iron:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 12
acacia:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 8
oak:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 7
jungle:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 6
birch:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 5
dark_oak:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 4
spruce:
  velocity:
    horizontal: 0.05
    vertical: 0.3
  range: 3
fall: 0.35
limit: 12
limit_block: iron